### PR TITLE
Add `sourceType` option

### PR DESCRIPTION
**Pull request by brechtcs**
This implements the second change described in https://github.com/goto-bus-stop/browser-pack-flat/issues/30.

I'm a bit less sure about this implementation. An alternative would be to rewrite:

```js
function parseModule (opts) {
  return function (row, index, rows) {
    // parseModule code
  }
}
```

and then do:

```js
rows.forEach(parseModule(opts))
```

But I chose to do `parseModule.bind(opts)` instead, because it touches much less lines of code, so it doesn't mess up the version history as much. Do let me know what you think though!

### CODE REVIEW

**Comment by goto-bus-stop** [comment]
I'm not sure what this would do—it would not crash on ES module syntax in input files but browser-pack-flat doesn't do anything with it, so it'd just be passed straight through. is that the intent?

my preference would be something like this:
```js
rows.forEach(function (row, index) { parseModule(opts, row, index, rows) })
```
then it's still clear where the `.sourceType` property comes from

**Comment by brechtcs** [comment]
Right, I'm using babelify with [this plugin](https://github.com/tbranyen/babel-plugin-transform-commonjs) to transform CommonJS exports into ESM exports. So by the time browserify gets to the `pack` stage, there's ESM code in there. With the standard `browser-pack` module this is no problem, because it doesn't do any further parsing. With `browser-pack-flat` though, acorn crashes on this if `sourceType` isn't set to 'module'.

I'll update the implementation to match you suggestion.

**Comment by goto-bus-stop** [comment]
Does webrunify work with this patch if you manually apply it inside node_modules? browser-pack-flat uses require() calls and module.exports assignments to do its dependency analysis and to remove the unnecessary stuff, for example `module.exports =` assignments are replaced by variable assignments. If those are replaced by `export default` before browser-pack-flat runs it won't be able to resolve them I think.

I don't mind taking this patch if it works but i'd be surprised if it does, I think you may have to do the CJS → ESM transform _after_ browser-pack-flat.

**Comment by brechtcs** [comment]
Excellent point. I had in fact tested this, but only on single-file modules requiring from NPM and/or node builtins. This worked because babelify doesn't touch external dependendies. When I tested it with `require('./local')` though, it was in fact broken. I [fixed this](https://github.com/brechtcs/webrunify/commit/20bfc6fd70a8e778d4e3430d6f76db6fc319d8ad) by setting up babelify to run only against entry files, and it works now for local requires too. Thanks for the thorough review, helping me to catch this bug early!

I also updated the implementation of this PR to match your recommendation. If you have any further issues/questions, fire away! :)

**Pull request merged**
